[connections.snowflake]
account = "xxxxxxx-xxxxxxx"
user = "Lily"
password ='Yay123456'
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
